---
title: "BDL"
output: html_notebook
---

```{r}
devtools::install_github("statisticspoland/R_Package_to_API_BDL")
library(bdl)

get_subjects()
get_subjects(parentId = "K3")
get_subjects(parentId = "G535")
get_subjects(parentId = "P1347")

search_subjects("rozwody")
```

```{r}
get_variables(subjectId = "P1347")

search_variables("stopa", level = 5, year = 2015)
```

```{r}
get_units(level = 2)

search_units("poznań")
```

```{r}
dane <- get_data_by_variable(varId = "60270", 
                             unitLevel = 5, 
                             year = 2015:2018)
```

```{r}
options(bdl.api_private_key="qwertyuiopasdfghjklzxcvbnm")
poznan <- get_data_by_unit(unitId = "023016100000", 
                           varId = c("60270", "64428"),
                           type = "label")
```

# Modele panelowe

```{r}
stopa_bezr <- get_data_by_variable(varId = "60270", unitLevel = 2, 
                                   year = 2010:2018)

ludnosc <- get_data_by_variable(varId = "60566", unitLevel = 2, 
                                year = 2010:2018)

library(tidyverse)

stopa_bezr <- stopa_bezr %>% 
  select(-id, -attrId, stopa_bezr=val)

ludnosc <- ludnosc %>% 
  select(-id, -attrId, udzial_lud=val)

dane_model <- inner_join(stopa_bezr, ludnosc)

ggplot(dane_model, aes(x = name, y = stopa_bezr)) +
  geom_boxplot() +
  coord_flip()
```

```{r}
library(plm)

m_pooling <- plm(formula = stopa_bezr ~ udzial_lud, 
                 data = dane_model, 
                 model = "pooling", 
                 index = c("name", "year"))
summary(m_pooling)
```

```{r}
m_lsdv <- plm(formula = stopa_bezr ~ udzial_lud + name - 1,
              data = dane_model,
              model = "pooling")

summary(m_lsdv)
```

```{r}
m_within <- plm(formula = stopa_bezr ~ udzial_lud,
                data = dane_model,
                model = "within")
summary(m_within)
```

```{r}
fixef(m_within)
```

```{r}
pFtest(m_within, m_pooling)
```

Lepszy jest model z efektami wewnątrzgrupowymi.

```{r}
m_between <- plm(formula = stopa_bezr ~ udzial_lud, 
                 data = dane_model,
                 model = "between")

summary(m_between)
```

```{r}
m_random <- plm(formula = stopa_bezr ~ udzial_lud, 
                data = dane_model,
                model = "random")

summary(m_random)
```

```{r}
ranef(m_random)
```

```{r}
phtest(m_random, m_within)
```

Lepszy jest model z efektami losowymi.













